<div class="jumbotron">
    <div class="row">
        <div class="col-sm-6">
            <h2>Listagem de Notícias</h2>
        </div>
        <div class="col-sm-6 text-right">
            <a class="btn btn-primary" href="<?=$this->basePath()?>/article/add"><i class="glyphicon glyphicon-plus"></i> Nova Notícia</a>
            <a class="btn btn-default" href="/article"><i class="glyphicon glyphicon-refresh"></i> Atualizar</a>
        </div>
    </div>
    <?php echo $this->partial('flash-message'); ?>
    <table class="table">
        <tr>
            <th width="15%">ID</th>
            <th width="75%">Título</th>
            <th colspan="2">Ações</th>
        </tr>
        <?php
        if (!empty($articles)) {
            foreach ($articles as $article) { ?>
                <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0", "#FFFFFF"))->next() ?>">
                    <td><?= $article['id'] ?></td>
                    <td><?= $article['title'] ?></td>
                    <td>
                        <a title="Visualizar notícia" class="btn btn-default btn-sm"
                           href="<?= $this->basePath() ?>/article/view/<?= $article['id'] ?>">
                            <i class="glyphicon glyphicon-eye-open text-primary"></i>
                        </a>
                    </td>
                    <td>
                        <a title="Editar notícia" class="btn btn-default btn-sm"
                           href="<?= $this->basePath() ?>/article/edit/<?= $article['id'] ?>">
                            <i class="glyphicon glyphicon-edit text-primary"></i>
                        </a>
                    </td>
                </tr>
        <?php
            }
        } else {
        ?>
            <tr>
                <td colspan="4" align="center">
                    Por algum motivo, não foi possível buscar os itens do WebService.<br>
                    Favor entrar em contato com o administrador do sistema!
                </td>
            </tr>
        <?php
        }
        ?>
    </table>

    <?php echo $this->partial('pager'); ?>
</div>