<div class="jumbotron">
    <h1>Listagem de Notícias</h1>
    <?php echo $this->partial('flash-message'); ?>
    <table class="table">
        <tr>
            <td colspan="4">
                <a class="btn btn-success" href="<?=$this->basePath()?>/article/add">Adicionar</a>
            </td>
        </tr>
        <tr>
            <th>ID</th>
            <th>Título</th>
            <th>Ver</th>
            <th>Modificar</th>
        </tr>
        <?php foreach($articles as $article){ ?>
            <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
                <td><?=$article['id']?></td>
                <td><?=$article['title']?></td>
                <td><a class="btn btn-success" href="<?=$this->basePath()?>/article/view/<?=$article['id']?>">Ver</a></td>
                <td><a class="btn btn-primary" href="<?=$this->basePath()?>/article/edit/<?=$article['id']?>">Modificar</a></td>
            </tr>
        <?php } ?>
    </table>

    <?php echo $this->partial('pager'); ?>
</div>