<script type="text/javascript" src="/js/enter.js"></script>
<div class="jumbotron">
    <h2>Cadastrar Notícia</h2>
    <hr class="border-top-color">
    <?php echo $this->partial('flash-message'); ?>

    <?php
    $form = $this->addArticleForm;
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <table>
        <tr>
            <td><?php echo $this->formlabel($form->get('title'));?></td>
            <td><?php echo $this->formElement($form->get('title')); ?>
                <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('title'));?></span></td>
        </tr>
        <tr>
            <td><?php echo $this->formlabel($form->get('subtitle'));?></td>
            <td><?php echo $this->formElement($form->get('subtitle')); ?>
                <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('subtitle'));?></span></td>
        </tr>
        <tr>
            <td><?php echo $this->formlabel($form->get('text'));?></td>
            <td><?php echo $this->formElement($form->get('text')); ?>
                <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('text'));?></span></td>
        </tr>
        <tr>
            <td><?php echo $this->formlabel($form->get('tags-string'));?></td>
            <td><?php echo $this->formElement($form->get('tags-string')); ?>
                <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('tags-string'));?></span></td>
        </tr>
        <tr>
            <td> </td>
            <td>
                <button type="submit" class="btn btn-primary" name="submit">
                    <span class="glyphicon glyphicon-plus"></span> &nbsp; Salvar
                </button>
                <a href="<?=$_SERVER['HTTP_REFERER']?>" class="btn btn-large btn-success"><i class="glyphicon glyphicon-backward"></i> &nbsp; Voltar</a>
            </td>
        </tr>
    </table>
    <?php
    $this->QuCKEditor(
        'editor',
        array('width' => "100%",
            'height' => "300",
            'uiColor' => '#FFFFFF',
        )
    );
    echo $this->form()->closeTag($form);
    ?>
</div>