<div class="jumbotron">
    <h2><?=$article['title']?></h2>
    <h3><?=$article['subtitle']?></h3>
    <div><?=$article['text']?></div>
    <div>
        <a class="btn btn-success" href="<?=$this->basePath()?>/article/edit/<?=$article['id']?>">
            <i class="glyphicon glyphicon-edit"></i> &nbsp; Editar
        </a>
        <a class="btn btn-primary" href="<?=$_SERVER['HTTP_REFERER']?>">
            <i class="glyphicon glyphicon-backward"></i> &nbsp; Voltar
        </a>
    </div>
</div>