<?php
use Application\Controller\LoginController;

$active_page = basename($_SERVER['PHP_SELF'], ".php");

echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('UFMG Test'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('bootstrap-tagsinput/bootstrap-tagsinput.css')); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <header class="navbar navbar-default navbar-fixed-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('UFMG Test') ?>
                    </a>
                </div>
                <nav class="collapse navbar-collapse" role="navigation">
                    <ul class="nav navbar-nav">
                        <li class="<?= ($active_page === 'index') ? 'active':'noactive'; ?>">
                            <a href="<?php echo $this->url('home') ?>">
                                <span class="glyphicon glyphicon-home"></span>&nbsp;<?php echo $this->translate('Home') ?>
                            </a>
                        </li>
                        <li class="<?= ($active_page === 'article') ? 'active':'noactive'; ?>">
                            <a href="<?php echo $this->url('article') ?>">
                                <span class="glyphicon glyphicon-folder-open"></span>&nbsp;<?php echo $this->translate('Gerenciar Notícias') ?>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-right navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <span class="glyphicon glyphicon-user"></span>&nbsp;<?php echo $this->message ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" style="padding:12px;">
                                <?php if (LoginController::getSession()->offsetExists('access_token')) { ?>
                                    <li><a href="#"><span class="glyphicon glyphicon-user"></span>&nbsp;Ver Perfil</a></li>
                                    <li><a href="<?php echo $this->url('logoff') ?>"><span class="glyphicon glyphicon-log-out"></span>&nbsp;Sair</a></li>
                                <?php } else {?>
                                    <li><a href="<?php echo $this->url('login') ?>"><span class="glyphicon glyphicon-log-in"></span>&nbsp;Entrar</a></li>
                                <?php }?>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </header>

        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <hr>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <ul class="list-inline">
                            <li><i class="fa fa-facebook fa-2x"></i></li>
                            <li><i class="fa fa-twitter fa-2x"></i></li>
                            <li><i class="fa fa-google-plus fa-2x"></i></li>
                            <li><i class="fa fa-pinterest fa-2x"></i></li>
                        </ul>

                    </div>
                    <div class="col-sm-6">
                        <p class="pull-right">&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                    </div>
                </div>
            </div>
        </footer>
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath('bootstrap-tagsinput/bootstrap-tagsinput.min.js')); ?>
    </body>
</html>
