<div class="jumbotron">
    <h1>Editar Notícia</h1>
    <?php echo $this->partial('flash-message'); ?>

    <?php
    $form = $this->editArticleForm;
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <table>
        <tr>
            <td><?php echo $this->formlabel($form->get('title'));?></td>
            <td><?php echo $this->formElement($form->get('title')); ?>
                <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('title'));?></span></td>
        </tr>
        <tr>
            <td><?php echo $this->formlabel($form->get('subtitle'));?></td>
            <td><?php echo $this->formElement($form->get('subtitle')); ?>
                <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('subtitle'));?></span></td>
        </tr>
        <tr>
            <td><?php echo $this->formlabel($form->get('text'));?></td>
            <td><?php echo $this->formElement($form->get('text')); ?>
                <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('text'));?></span></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
                <a class="btn btn-primary" href="<?=$_SERVER['HTTP_REFERER']?>">Voltar</a>
                <?php echo $this->formElement($form->get('submit')); ?>
            </td>
        </tr>
    </table>
    <?php
    echo $this->form()->closeTag($form);

    $this->QuCKEditor(
        'editor',
        array('width' => "100%",
            'height' => "300",
            'uiColor' => '#FFFFFF',
        )
    );
    ?>
</div>